title: stuetnunc
author: mathMakesArt-stumats
email: mathmakesart@gmail.com
description: > # this means to ignore newlines
  stuetnunc is a fork of mathMakesArt theme for Jekyll websites,
  specifically designed for use by artists
  on the HicEtNunc platform
# social links
github_username:  stumats
twitter_username: stusontier
instagram_username: stusontierphoto


# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b, %Y"


# Build settings
markdown: kramdown
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
 
 # Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/
  - ignore/
